### PR TITLE
Class authority syntax

### PR DESCRIPTION
**Pull request by rwp0**
Class authority will probably be declared using KIM in the future.

### CODE REVIEW

**Comment by Ovid** [comment]
Hi @rwp0. Thanks! With KIM syntax, it's more likely to be this:

```perl
class Foo :authority(cpan:OVID) { ... }
```

Would you like to update this and I'll merge?

Best,
Ovid

**Comment by rwp0** [comment]
Ah yes; sure, will do that now.

**Comment by rwp0** [comment]
Done

**Comment by Ovid** [comment]
Thank you :)

**Pull request merged**
